${PYTHON} = python3
${DIR} = infected/

run:
	${PYTHON} stockholm.py

h:
	${PYTHON} stockholm.py -h
help:
	${PYTHON} stockholm.py --help

r:
	${PYTHON} stockholm.py -r
reverse:
	${PYTHON} stockholm.py --reverse

s:
	${PYTHON} stockholm.py -s
silent:
	${PYTHON} stockholm.py --silent

v:
	${PYTHON} stockholm.py -v
version:
	${PYTHON} stockholm.py --version
